clone:
  fetch_source_code:
    image: plugins/git
    depth: 1

pipeline:
  prepare_build_tags:
    image: registry.asseco.rs/asseco/image-tagger
    secrets: [ GITHUB_TOKEN ]

  build_event_bus:
    image: microsoft/aspnetcore-build
    commands:
      - cd EventBus
      - dotnet build
      - dotnet pack --configuration Release /p:PackageVersion=$(head -n 1 ../.version)
      - cd bin/Release
      - dotnet nuget push *.nupkg -s http://packages.asseco.rs:30888/repository/nuget -k $NUGET_KEY
    secrets: [ NUGET_KEY ]

  build_event_bus_active_mq:
    image: microsoft/aspnetcore-build
    commands:
      - cd EventBusActiveMQ
      - dotnet build
      - dotnet pack --configuration Release /p:PackageVersion=$(head -n 1 ../.version)
      - cd bin/Release
      - dotnet nuget push *.nupkg -s http://packages.asseco.rs:30888/repository/nuget -k $NUGET_KEY
    secrets: [ NUGET_KEY ]

  tag_latest_event_bus:
    image: microsoft/aspnetcore-build
    commands:
      - cd EventBus
      - dotnet restore
      - dotnet setversion $(head -n 1 ../.version)
    when:
      event: tag

  tag_latest_event_bus_active_mq:
    image: microsoft/aspnetcore-build
    commands:
      - cd EventBusActiveMQ
      - dotnet setversion $(head -n 1 ../.version)
    when:
      event: tag

  git_push:
    image: bravissimolabs/alpine-git
    commands:
      - git checkout -b master
      - git config --global user.name "$GIT_NAME"
      - git config --global user.email "$GIT_EMAIL"
      - git add .
      - git commit -m "Drone automated commmit build - $DRONE_BUILD_NUMBER [CI SKIP]"
      - git pull origin master
      - git push origin master
    secrets: [ GIT_NAME, GIT_EMAIL, GITHUB_TOKEN, GITHUB_NAME ]
    when:
      event: tag

  slack_notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: drone
    username: drone
    when:
      status: [ failure ]
    template: >
      {{#success build.status}}
        Repo {{repo.name}} build {{build.number}} succeeded. Good job {{build.author}}!
      {{else}}
        Repo {{repo.name}} build {{build.number}} failed. <@{{build.author}}> fix me please!
      {{/success}}
